---
namespace: bec
name: shell

version: 1.1.4
readme: README.md
authors:
  - Patrick Becker

description: A simple collection to install and set up a shell on Linux.

license:
  - MIT

tags:
  - zsh
  - zshell
  - shell
  - terminal
  - console
  - zshrc
  - zshenv
  - zprofile
  - zlogin
  - zlogout
  - application
  - linux

dependencies: {}

repository: https://github.com/bec-galaxy/bec.shell
documentation: https://github.com/bec-galaxy/bec.shell
homepage: https://github.com/bec-galaxy
issues: https://github.com/bec-galaxy/bec.shell/issues

build_ignore:
  - "*.tar.gz"
