---
- name: Ensure variables are set
  ansible.builtin.assert:
    that:
      - zsh_dependencies is defined
      - zsh_executable is defined
      - zsh_config_mode is defined
      - zsh_config_backup is defined
      - zsh_config_overwrite is defined
      - zsh_users is defined
      - zsh_users_config is defined
      - zsh_system_config is defined

- name: Ensure zsh with dependencies are installed
  ansible.builtin.apt:
    name: "{{ ['zsh'] + zsh_dependencies }}"
    state: present
    update_cache: true
  become: true
  tags:
    - zsh
    - dependencies

- name: Distribute zsh system files
  ansible.builtin.include_tasks: system.yml
  tags:
    - zsh
    - config
    - system

# Make sure that the default shell is zsh and the user files are distributed.
- name: Distribute zsh user files
  ansible.builtin.include_tasks: users.yml
  loop: "{{ zsh_users }}"
  tags:
    - zsh
    - config
    - user
