---
- name: Verify that the user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"
  become: true
  tags:
    - zsh
    - shell
    - user

- name: Ensure zsh is the default shell
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ zsh_executable }}"
  register: user
  become: true
  tags:
    - zsh
    - shell
    - user

- name: Create zsh user files
  ansible.builtin.template:
    src: "{{ config.template }}"
    dest: "{{ (user.home, config.filename) | path_join }}"
    mode: "{{ zsh_config_mode }}"
    backup: "{{ zsh_config_backup }}"
    force: "{{ zsh_config_overwrite }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  loop: "{{ zsh_users_config }}"
  loop_control:
    loop_var: config
  become: true
  tags:
    - zsh
    - config
    - user
